export const labels = { work: '作品', knowledge: '知识', question: '提问', chat: '闲聊', pending: '待审核', approved: '已发布', rejected: '已退回', active: '已加入', confirmed: '报名成功', waiting: '候补中', cancelled: '已取消', open: '报名开放', completed: '交接完成', expired: '已过期' };
export const h = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const date = value => new Date(value).toLocaleString('zh-CN', { month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' });
export const tag = status => `<span class="tag ${h(status)}">${h(labels[status] || status)}</span>`;
export const head = (title, subtitle = '', extra = '') => `<div class="page-head"><div><span class="eyebrow">TONGPING / CLUB SPACE</span><h1>${h(title)}</h1><p>${h(subtitle)}</p></div>${extra}</div>`;
export const empty = (title, text, link = '#compose', action = '发布第一条内容') => `<div class="state"><h2>${h(title)}</h2><p>${h(text)}</p><a class="button primary" href="${h(link)}">${h(action)}</a></div>`;
export const pager = (offset, count, size = 12) => `<div class="pagination"><button data-page="${Math.max(0,offset-size)}" ${offset === 0 ? 'disabled' : ''}>上一页</button><span class="muted">第 ${Math.floor(offset/size)+1} 页</span><button data-page="${offset+size}" ${count < size ? 'disabled' : ''}>下一页</button></div>`;
export const review = (type, id) => `<form class="review-box" data-form="review" data-type="${type}" data-id="${h(id)}"><label>处理说明<textarea name="reason" maxlength="500" aria-label="退回理由" placeholder="退回时必填：帮助作者知道如何改进"></textarea></label><div class="actions"><button class="primary" name="status" value="approved">通过审核</button><button class="danger" name="status" value="rejected">退回修改</button></div></form>`;
export function postCard(p, demo) {
  const cover = p.media_id ? `<img class="cover" data-media="${h(p.media_id)}" alt="${h(p.title)}的作品图片">` : demo && p.id === 'forest' ? '<img class="cover" src="/forest.svg" alt="几何森林场景演示作品">' : '';
  return `<article class="card"><a href="#post/${h(p.id)}">${cover}<div class="card-pad"><div class="meta"><span class="avatar">${h(p.author_name?.slice(0,1))}</span><span>${h(p.author_name)}</span><span>${h(date(p.created_at))}</span>${tag(p.kind)}</div><h2>${h(p.title)}</h2><p>${h(p.body.slice(0,100))}${p.body.length > 100 ? '…' : ''}</p>${p.feedback ? `<div class="feedback"><strong>希望听听你的建议</strong>${h(p.feedback)}</div>` : ''}<div class="card-end">${tag(p.status)}<span>查看与回应 ↗</span></div></div></a></article>`;
}
export function compose() {
  return `${head('发布一点新东西','不必等到完美。让同伴知道，你希望收到哪一种回应。')}<div class="detail card card-pad"><form class="form" data-form="compose"><label>内容类型<select name="kind"><option value="work">作品 / 半成品</option><option value="knowledge">知识分享</option><option value="question">向社团提问</option><option value="chat">日常闲聊</option></select></label><label>标题<input name="title" required maxlength="100" placeholder="给这次分享起个名字"></label><label>正文<textarea name="body" required maxlength="10000" placeholder="你做了什么？遇到什么问题？"></textarea></label><label>想听到哪方面的反馈？<input name="feedback" maxlength="500" placeholder="比如：构图、节奏、实现方式……"></label><label>作品图片（可选）<input name="image" type="file" accept="image/png,image/jpeg,image/webp"><small>一张图片，最大 5 MB。上传会重新编码并去除元数据。</small></label><div class="feedback"><strong>可见范围：仅当前社团</strong>投稿通过人工审核后，其他成员才能看见。不会自动发布到校外。</div><label class="check"><input name="consent" type="checkbox" required><span>我确认拥有发布权限，并同意社团成员查看与反馈。</span></label><div class="form-actions"><button class="primary" type="submit">提交审核</button><a class="button" href="#mine">查看我的投稿</a></div></form></div>`;
}
export function eventCard(event) {
  return `<article class="card card-pad"><div class="event-date">${h(date(event.starts_at))}</div><h2>${h(event.title)}</h2><p>${h(event.location)}</p><div class="badge-line">${tag(event.status)}${event.my_registration ? tag(event.my_registration) : ''}</div><div class="card-end"><span>${event.confirmed} / ${event.capacity} 人已报名 · ${event.waiting} 人候补</span><a href="#event/${h(event.id)}">查看活动 ↗</a></div></article>`;
}
export function eventForm() {
  return `${head('发起社团活动','时间使用你当前设备的时区，服务端统一存储为 UTC。')}<div class="detail card card-pad"><form class="form" data-form="event"><label>活动名称<input name="title" minlength="2" maxlength="100" required></label><label>活动说明<textarea name="description" minlength="2" maxlength="5000" required></textarea></label><label>地点<input name="location" maxlength="200" required></label><div class="form-row"><label>开始时间<input name="starts_at" type="datetime-local" required></label><label>结束时间<input name="ends_at" type="datetime-local" required></label></div><label>名额<input name="capacity" type="number" min="1" max="1000" value="20" required></label><small>名额已满时进入候补队列，取消报名后按顺序递补。首版不提供签到。</small><button class="primary" type="submit">发布活动</button></form></div>`;
}
export function login(demo) {
  return `<div class="card login-box"><span class="eyebrow">A SPACE TO GROW, TOGETHER</span><h1>让作品有回应，<br>让经验有传承。</h1><p class="muted">这是社团成员的共同空间。登录只建立账号，入社还需要社长审核。</p>${demo ? `<form class="form" data-form="login"><label>选择演示身份<select name="persona"><option value="member">林杳 · 社团成员</option><option value="owner">陈序 · 社长</option><option value="next">周周 · 另一位成员</option><option value="applicant">新同学 · 申请入社</option><option value="outsider">夏禾 · 其他社团成员</option></select></label><button class="primary">进入演示社团</button><small>仅本地演示可切换身份；不是生产环境的身份验证方式。</small></form>` : `<form class="form" data-form="session"><label>会话令牌<input type="password" name="token" required autocomplete="off"></label><button class="primary">使用本人会话登录</button><small>浏览器仅用于联调。正式入口请使用微信/QQ 小程序；令牌仅存于当前页面内存，刷新后需重新登录。</small></form>`}</div>`;
}
